config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: "users/passwords",
    omniauth_callbacks: 'users/omniauth_callbacks',

  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/details", to: "home#details"
  get "/enrol_now/:course_id", to: "home#enrol_now", as: :enrol_now
  get "/contact", to: "home#contact", as: :contact
  post "/contact", to: "home#submit_contact_query", as: :submit_contact_query


  resources :courses
  get "/course_details", to: "courses#details"
  post "/enrol", to: "courses#enrol", as: :enrol
  get "/users/:id/dashboard", to: "users_home#dashboard", as: :user_dashboard
  get "/users/:id/dashboard", to: "users_home#dashboard", as: :users_root

  get "/users/:id/profile", to: "users_home#get_profile", as: :get_user_profile
  post "/users/:id/profile", to: "users_home#update_profile", as: :update_user_profile
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

	def details
	end

	def enrol_now
		course_id = params[:course_id]
		@course = Course.find_by(id: course_id)
	end

	def contact
	end

	def submit_contact_query
		ContactFormQuery.create(contact_params)
		redirect_to root_path, notice: "Your query is submitted. We will get back to you soon :)"
	end


	private

	def contact_params
		params.require(:contact).permit(:first_name, :last_name, :email, :query_text)
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<style>
    .btn-lnk{
        background: transparent!important;
        border: none;
        /*padding: 0!important;*/
        /*optional*/
        font-family: 'Roboto', sans-serif;
        font-size: 16px;
        /*input has OS specific font-family*/
        color: #9D9D9D;
        text-decoration: none;
        cursor: pointer;
        padding-bottom: 15px;
        padding-top: 15px;
        line-height: 20px;
        position: relative;
        font-weight: 400;
        /*padding: 10px 15px;*/
    }
</style>

<nav class="navbar navbar-inverse" style="margin-bottom: 0; background-color: #253237; position: sticky; top: 0; z-index: 1000">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
<span class="icon-bar"></span>
        <span class="icon-bar"></span>
<span class="icon-bar"></span>
      </button>
<a class="navbar-brand" href="/">YourCSLab</a>
    </div>
<div class="collapse navbar-collapse" id="myNavbar">
<ul class="nav navbar-nav">
  <% if current_user.present? %>
    <li><a href="<%= user_dashboard_path(current_user.id) %>">Home</a></li>
  <% end %>
<!--<li class="active"><a href="#">Home</a></li>-->
<!--<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Courses <span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="#">Page 1-1</a></li>
<li><a href="#">Page 1-2</a></li>
<li><a href="#">Page 1-3</a></li>
</ul>
        </li>-->
<li><a href="#">About</a></li>
<li><a href="<%= contact_path %>">Contact</a></li>
</ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.present? %>
          <li>
            <%= button_to "Log Out", destroy_user_session_path, :method => :delete, :class => "btn-lnk", :confirm => "Are you sure ?"%>
          </li>
          <% else %>
          <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user fw-bolder"></span> Sign Up </a></li>
          <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
          <% end %>

      </ul>
</div>
  </div>
</nav>

app/views/home/contact.html.erb
<style>
    body {
        background-color: #f2f7fb;
        background-image: url("https://images.pexels.com/photos/1714205/pexels-photo-1714205.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2")
    }

    .login-block {
        margin: 30px auto;
        min-height: 93.6vh
    }

    .login-block .auth-box {
        margin: 20px auto 0;
        max-width: 450px !important
    }

    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 0 5px 0 rgba(43, 43, 43, .1), 0 11px 6px -7px rgba(43, 43, 43, .1);
        box-shadow: 0 0 5px 0 rgba(43, 43, 43, .1), 0 11px 6px -7px rgba(43, 43, 43, .1);
        border: none;
        margin-bottom: 30px;
        -webkit-transition: all .3s ease-in-out;
        transition: all .3s ease-in-out;
        background-color: #fff;
    }

    .card .card-block {
        padding: 1.25rem
    }

    .f-80 {
        font-size: 80px
    }

    .form-group {
        margin-bottom: 1.25em
    }

    .form-material .form-control {
        display: inline-block;
        height: 43px;
        width: 100%;
        border: none;
        border-radius: 0;
        font-size: 16px;
        font-weight: 400;
        padding: 9px;
        background-color: transparent;
        -webkit-box-shadow: none;
        box-shadow: none;
        border-bottom: 1px solid #ccc
    }

    .btn-md {
        padding: 10px 16px;
        font-size: 15px;
        line-height: 23px
    }

    .btn-primary {
        background-color: #154F56;
        border-color: #154F56;
        color: #fff;
        cursor: pointer;
        -webkit-transition: all ease-in .3s;
        transition: all ease-in .3s
    }

    .btn {
        border-radius: 2px;
        text-transform: capitalize;
        font-size: 15px;
        padding: 10px 19px;
        cursor: pointer
    }

    .m-b-20 {
        margin-bottom: 20px
    }

    .btn-md {
        padding: 10px 16px;
        font-size: 15px;
        line-height: 23px
    }

    .heading{

        font-size: 21px;

    }

    #infoMessage p{

        color: red !important;
    }


    .btn-google {
        color: #545454;
        background-color: #ffffff;
        box-shadow: 0 1px 2px 1px #ddd;
    }


    .or-container {
        align-items: center;
        color: #ccc;
        display: flex;
        margin: 25px 0;
    }

    .line-separator {
        background-color: #ccc;
        flex-grow: 5;
        height: 1px;
    }

    .or-label {
        flex-grow: 1;
        margin: 0 15px;
        text-align: center;
    }
</style>

<section class="login-block">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <%= form_tag(url: submit_contact_query_path, method: :post, class: "md-float-material form-material") do |f| %>
          <div class="auth-box card">
            <div class="card-block">
              <div class="row">
                <div class="col-md-12">
                  <h3 class="text-center heading" >Submit your Query</h3>

                </div>
              </div>
              <div class="form-group form-primary">
                <%= text_field_tag :first_name, "", autofocus: true, autocomplete: "first_name", class: "form-control", placeholder: "First Name", id: "first_name", name: "contact[first_name]" %>
              </div>
              <div class="form-group form-primary">
                <%= text_field_tag :last_name, "", autofocus: true, autocomplete: "last_name", class: "form-control", placeholder: "Last Name", id: "last_name", name: "contact[last_name]" %>
              </div>

              <div class="form-group form-primary">
                  <%= email_field_tag :email, "", autofocus: true, autocomplete: "email", class: "form-control", placeholder: "Email", id: "email", name: "contact[email]" %>
              </div>

              <div class="form-group form-primary">
                <%= text_area_tag :query, "", autofocus: true, autocomplete: "query_text", class: "form-control", placeholder: "Query/Message", id: "query_text", name: "contact[query_text]" %>
              </div>

              <div class="row">
                <div class="col-md-12">
                  <input type="submit" class="btn btn-primary btn-md btn-block waves-effect text-center m-b-20" name="submit" value="Submit">
                </div>
              </div>
              <br>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/home/details.html.erb
<style>
    #misseling h1 {
        margin: 0;
        font-size: 48px;
        font-weight: 700;
        line-height: 56px;
        /*text-transform: uppercase;*/
        color: #2c4964;
    }
    #misseling p {
        font-family: "Raleway", sans-serif;
        font-weight: 500;
        font-size: 20px;
        letter-spacing: 1px;
    }
  </style>

<section id="misseling" class="d-flex align-items-center mt-5">
  <div class="container mt-5">
    <h1>Claim Rejection</h1>
    <p>ncdkfjvvevivhvivdhdi</p>
  </div>
</section>

app/views/home/enrol_now.html.erb
<style>
    body {
        background-color: #f2f7fb;
        background-image: url("https://images.pexels.com/photos/1714205/pexels-photo-1714205.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2")
    }

    .login-block {
        margin: 30px auto;
        min-height: 93.6vh
    }

    .login-block .auth-box {
        margin: 20px auto 0;
        max-width: 450px !important
    }

    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 0 5px 0 rgba(43, 43, 43, .1), 0 11px 6px -7px rgba(43, 43, 43, .1);
        box-shadow: 0 0 5px 0 rgba(43, 43, 43, .1), 0 11px 6px -7px rgba(43, 43, 43, .1);
        border: none;
        margin-bottom: 30px;
        -webkit-transition: all .3s ease-in-out;
        transition: all .3s ease-in-out;
        background-color: #fff;
    }

    .card .card-block {
        padding: 1.25rem
    }

    .f-80 {
        font-size: 80px
    }

    .form-group {
        margin-bottom: 1.25em
    }

    .form-material .form-control {
        display: inline-block;
        height: 43px;
        width: 100%;
        border: none;
        border-radius: 0;
        font-size: 16px;
        font-weight: 400;
        padding: 9px;
        background-color: transparent;
        -webkit-box-shadow: none;
        box-shadow: none;
        border-bottom: 1px solid #ccc
    }

    .btn-md {
        padding: 10px 16px;
        font-size: 15px;
        line-height: 23px
    }

    .btn-primary {
        background-color: #154F56;
        border-color: #154F56;
        color: #fff;
        cursor: pointer;
        -webkit-transition: all ease-in .3s;
        transition: all ease-in .3s
    }

    .btn {
        border-radius: 2px;
        text-transform: capitalize;
        font-size: 15px;
        padding: 10px 19px;
        cursor: pointer
    }

    .m-b-20 {
        margin-bottom: 20px
    }

    .btn-md {
        padding: 10px 16px;
        font-size: 15px;
        line-height: 23px
    }

    .heading{

        font-size: 21px;

    }

    #infoMessage p{

        color: red !important;
    }

</style>

<%= render partial: "home/header" %>
<section class="login-block">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <!--        <form class="md-float-material form-material" action="/enrol" method="POST">-->
          <%= form_tag('/enrol', method: :post, class: "md-float-material form-material") do %>
            <div class="auth-box card">
              <div class="card-block">
                <div class="row">
                  <div class="col-md-12">
                    <h3 class="text-center heading">Enrolment Form</h3>

                  </div>
                </div>
                <!--           <div class="form-group form-primary">
                             <input type="text" class="form-control" name="first_name" value="" placeholder="First Name" id="first_name">
                           </div>
                           <div class="form-group form-primary">
                             <input type="text" class="form-control" name="last_name" value="" placeholder="Last Name" id="last_name">
                           </div>
                           <div class="form-group form-primary">
                             <input type="text" class="form-control" name="email" value="" placeholder="Email" id="email">
                           </div>
                           <div class="form-group form-primary">
                             <input type="text" class="form-control" name="phone" value="" placeholder="Phone" id="phone">
                           </div>-->
                <div class="form-group form-primary">
                  <%= select_tag "course", options_for_select(Course.all.collect{ |u| [u.name, u.id]}, @course.id), {:class =>"form-control form-select", prompt: 'Select Course'} %>
                </div>
                <div class="form-group form-primary">
                  <input disabled type="text" class="form-control disabled" name="price" value="" placeholder="Price" id="price">
                </div>
                <div class="form-group form-primary">
                  <input disabled type="text" class="form-control disabled" name="discount" value="" placeholder="Discount" id="discount">
                </div>
                <div class="row">
                  <div class="col-md-12">
                    <input type="submit" class="btn btn-primary btn-md btn-block waves-effect text-center m-b-20" name="submit" value="Enrol Now">
                  </div>
                </div>

              </div>
            </div>
            <!--        </form>-->
          <% end %>
        </div>
      </div>
    </div>
  </section>


<script>
    $('select').on('change', function() {
        $.ajax({
            type: "GET",
            url: "<%= courses_path %>/"+ this.value,
            success: function (data) {
                $("#price").val("Price : $" + data.price);
                $("#discount").val("Price after " + data.discount + "% discount : $"  + (parseInt(data.price)-(parseInt(data.price)*parseInt(data.discount)/100)).toString());
            }
        });
    });
</script>

app/views/home/index.html.erb
<style>
body {
  font-family: 'Roboto', sans-serif;
}

ul {
  list-style: none;
  display: flex;
  justify-content: flex-end;
}

figure img {
  width: 100%;
  height: auto;
}

figure {
  margin-bottom: 30px;
}

header nav {
  display: flex;
  justify-content: flex-end;
}

div > h1 {
  font-size: 1.8rem;
}

nav > p {
  cursor: pointer;
}
.pill-black, .pill-white {
  border: 0.5px solid;
  border-radius: 5px;
  text-align: center;
}

.pill-black {
  background-color: #000000;
  color: #FFFFFF;
}

footer {
  margin-top: 20px;
}

footer div {
  display: flex;
  align-items: center;
}

/* Customizations of Bootstrap classes */

header .row {
  display: flex;
  align-items: center;
}

.col-sm-4 p {
  margin: 25px 20px 15px;
  min-width: 60px;
  padding: 1px;
}

section.container .row {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  justify-content: center;
}

.jumbotron {
  display: flex;
  align-items: center;
  height: 350px;
  background-image: url("https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg");
  background-size: cover;
  background-position: center;
}

.jumbotron h2 {
  background-color: #FFFFFF;
  display: inline-block;
  color: #36454F;
  font-weight: 700;
  padding: 10px 35px;
  border-radius: 5px;
}

.jumbotron h3 {
  color: #FFFFFF;
  font-weight: bold;
}

.col-sm-1 img {
  min-width: 32px;
  min-height: 33px;
}

.card {
	background:#154F56;
	color:white;
	height:28rem;
	border-radius: 1.25rem;
  padding: 10px;
}
.card-title{
  text-align: center;
  padding-top: 10px;
  font-weight: bold;
}

.price-div{
    padding-top: 10px;
    padding-left: 10px;
    padding-right: 10px;
}
.price{
    font-weight: bold;
    font-size: medium;
    float: left;
}
.detail-link{
    float: right;
}
.detail-link a {
    text-decoration: none;
    color: white;
    font-size: medium;
}

.detail-link a:hover {
    color: white;
    text-decoration: none;
    cursor: pointer;
}
.enrol-btn{
    margin-top: 32px;
    display: flex;
    justify-content: center;
    align-items: center;
}
.enrol-btn a{
    padding: 10px 20px 10px 20px;
    text-decoration: none;
    color: #154F56;
    font-weight: bold;
}
</style>

<section class="jumbotron">
  <div class="container">
    <div class="row text-center">
      <h2>Learn New Technologies</h2>
    </div>
  </div>
</section>


<div id="viewport">
  <section class="container">
    <%
      Course.all.in_batches(of: 3) do |courses|
    %>
      <div class="row">
        <% courses.each do |course|%>
          <div class="col-sm-4 mb-3 d-flex align-items-stretch">
            <div class="card">
              <div class="card-body">
                <h3 class="card-title"><%= course.name %></h3>
                <p class="card-text"><%= course.description %></p>
                <div class="price-div"><span class="price">Price: C$<%= course.price %></span>
                  <span class="detail-link"><a href="#" class="">Details</a></span></div>
              </div>
            </div>
          </div>
        <%end %>
      </div>
      <br>
    <%end%>
  </section>
</div>