config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: "users/passwords",
    omniauth_callbacks: 'users/omniauth_callbacks',

  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/details", to: "home#details"
  get "/enrol_now/:course_id", to: "home#enrol_now", as: :enrol_now
  get "/contact", to: "home#contact", as: :contact
  post "/contact", to: "home#submit_contact_query", as: :submit_contact_query


  resources :courses
  get "/course_details", to: "courses#details"
  post "/enrol", to: "courses#enrol", as: :enrol
  get "/users/:id/dashboard", to: "users_home#dashboard", as: :user_dashboard
  get "/users/:id/dashboard", to: "users_home#dashboard", as: :users_root

  get "/users/:id/profile", to: "users_home#get_profile", as: :get_user_profile
  post "/users/:id/profile", to: "users_home#update_profile", as: :update_user_profile
  end

app/controllers/users_home_controller.rb
class UsersHomeController < ApplicationController
  layout 'user_layout'
  def dashboard
    user_id = params[:id]
    @user = User.find_by(id: user_id)
    @enrolled_courses = @user.courses
    # render(:layout => "user_layout")
  end

  def get_profile
    user_id = params[:id]
    @user = User.find_by(id: user_id)
  end

  def update_profile
    user_id = params[:id]
    @user = User.find_by(id: user_id)
    profile_params = update_profile_params
    if profile_params["password"].blank? || profile_params["password_confirmation"].blank?
      profile_params.delete("current_password")
      profile_params.delete("password")
      profile_params.delete("password_confirmation")
      @user.update(profile_params)
      redirect_to get_user_profile_path(@user.id)
    elsif profile_params["current_password"].present? && profile_params["password"].present? &&
      profile_params["password_confirmation"].present? &&
      profile_params["password"] == profile_params["password_confirmation"]
      if @user.valid_password?(params["current_password"])
        @user.reset_password(profile_params["password"], profile_params["password_confirmation"])
      end
      profile_params.delete("current_password")
      profile_params.delete("password")
      profile_params.delete("password_confirmation")
      @user.update(profile_params)
      redirect_to root_path
    end
  end

  private

  def update_profile_params
    params.permit("first_name", "last_name", "institute", "position", "phone", "email",
                  "address", "current_password", "password", "password_confirmation")
  end

end

app/helpers/users_home_helper.rb
module UsersHomeHelper
end

app/views/users_home/_sidebar.html.erb
<style>
    @import url('https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500');

    body {
        overflow-x: hidden;
        font-family: 'Roboto', sans-serif;
        font-size: 16px;
    }

    /* Toggle Styles */

    #viewport {
        padding-left: 250px;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
        transition: all 0.5s ease;
    }

    #content {
        width: 100%;
        position: relative;
        margin-right: 0;
    }

    /* Sidebar Styles */

    #sidebar {
        z-index: 1000;
        position: fixed;
        left: 250px;
        width: 250px;
        height: 100%;
        margin-left: -250px;
        overflow-y: auto;
        /*background: #37474F;*/
        background: #253236;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
        transition: all 0.5s ease;
    }

    #sidebar header {
        background-color: #263238;
        font-size: 20px;
        line-height: 52px;
        text-align: center;
    }

    #sidebar header a {
        color: #fff;
        display: block;
        text-decoration: none;
    }

    #sidebar header a:hover {
        color: #fff;
    }

    #sidebar .nav{

    }

    #sidebar .nav a{
        background: none;
        border-bottom: 1px solid #455A64;
        color: #CFD8DC;
        font-size: 14px;
        padding: 16px 24px;
    }

    #sidebar .nav a:hover{
        background: none;
        color: #ECEFF1;
    }

    #sidebar .nav a i{
        margin-right: 16px;
    }

    .name{
        background: none;
        color: #777777;
        font-size: 17px;
        /*padding: 16px 24px;*/
        /*padding-top: 15px;*/
        /*padding-bottom: 15px;*/
        /*!*line-height: 20px;*!*/
        /*display: block;*/
        position: relative;
        display: block;
        padding: 10px 15px;
    }


</style>
<div id="sidebar">
  <header>
<!--    <a href="#">Useful Links</a>-->
  </header>
  <ul class="nav" style="display: block">
    <li>
      <a href="<%= user_dashboard_path(current_user.id) %>">
        <i class="zmdi zmdi-view-dashboard"></i> Dashboard
      </a>
    </li>
    <li>
      <a href="<%= get_user_profile_path(current_user.id) %>">
        <i class="zmdi zmdi-link"></i> Profile
      </a>
    </li>
  </ul>
</div>
<!-- Content -->
<div id="content">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= courses_path %>">Register for New Courses</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-left">
        <li><p class="name">Hello, <%= current_user.display_name %></p></li>
      </ul>
    </div>
  </nav>
</div>

app/views/users_home/_user_header.html.erb
<nav class="navbar navbar-inverse sticky-top" style="margin-bottom: 0; background-color: #253237; position: sticky; top: 0; z-index: 1000">
<div class="container-fluid">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
<span class="icon-bar"></span>
        <span class="icon-bar"></span>
<span class="icon-bar"></span>
      </button>
<a class="navbar-brand" href="#">YourCSLab</a>
    </div>
<div class="collapse navbar-collapse" id="myNavbar">
<ul class="nav navbar-nav">
<li class="active"><a href="#">Home</a></li>
<li class="dropdown">
<a class="dropdown-toggle" data-toggle="dropdown" href="#">Courses <span class="caret"></span></a>
<ul class="dropdown-menu">
<li><a href="#">Page 1-1</a></li>
<li><a href="#">Page 1-2</a></li>
<li><a href="#">Page 1-3</a></li>
</ul>
        </li>
<li><a href="#">About</a></li>
<li><a href="#">Contact</a></li>
</ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user fw-bolder"></span> Sign Up </a></li>
<!--        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
<!--<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>-->
      </ul>
</div>
  </div>
</nav>

app/views/users_home/dashboard.html.erb
<style>
    body {
        font-family: 'Roboto', sans-serif;
    }

    ul {
        list-style: none;
        display: flex;
        justify-content: flex-end;
    }

    figure img {
        width: 100%;
        height: auto;
    }

    figure {
        margin-bottom: 30px;
    }

    header nav {
        display: flex;
        justify-content: flex-end;
    }

    div > h1 {
        font-size: 2.8rem;
        text-decoration: underline;
    }

    nav > p {
        cursor: pointer;
    }
    .pill-black, .pill-white {
        border: 0.5px solid;
        border-radius: 5px;
        text-align: center;
    }

    .pill-black {
        background-color: #000000;
        color: #FFFFFF;
    }

    footer {
        margin-top: 20px;
    }

    footer div {
        display: flex;
        align-items: center;
    }

    /* Customizations of Bootstrap classes */

    header .row {
        display: flex;
        align-items: center;
    }

    .col-sm-4 p {
        margin: 25px 20px 15px;
        min-width: 60px;
        padding: 1px;
    }

    section.container .row {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
    }

    .jumbotron h2 {
        background-color: #FFFFFF;
        display: inline-block;
        color: #36454F;
        font-weight: 700;
        padding: 10px 35px;
        border-radius: 5px;
    }

    .jumbotron h3 {
        color: #FFFFFF;
        font-weight: bold;
    }

    .btn-primary {
        color: #2e6da4;
        background-color: #FFFFFF;
    }

    .col-sm-1 img {
        min-width: 32px;
        min-height: 33px;
    }

    .card {
        background:#154F56;
        color:white;
        height: 30rem;
        border-radius: 1.25rem;
        padding: 10px;

    }
    .card-title{
        text-align: center;
        padding-top: 10px;
        font-weight: bold;
    }

    .price-div{
        padding-top: 10px;
        padding-left: 10px;
        padding-right: 10px;
        text-align: center;
    }
    .price{
        font-weight: bold;
        font-size: medium;
        float: left;
    }
    .detail-link{
        font-weight: bold;
        font-size: medium;
    }
    .detail-link a {
        text-decoration: none;
        color: white;
        font-size: medium;
    }

    .detail-link a:hover {
        color: white;
        text-decoration: none;
        cursor: pointer;
    }
    .enrol-btn{
        margin-top: 32px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .enrol-btn a{
        padding: 10px 20px 10px 20px;
        text-decoration: none;
        color: #154F56;
        font-weight: bold;
    }


    .modal-row {
        display: flex;
        align-items: center;
    }

    .thank-you-card{
       height: auto;
    }

</style>


<style>
    @import url('https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500');

    body {
        overflow-x: hidden;
        font-family: 'Roboto', sans-serif;
        font-size: 16px;
    }

    /* Toggle Styles */

    #viewport {
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
        transition: all 0.5s ease;
    }

    #content {
        width: 100%;
        position: relative;
        margin-right: 0;
    }

    /* Sidebar Styles */

    #sidebar {
        z-index: 1000;
        position: fixed;
        left: 250px;
        width: 250px;
        height: 100%;
        margin-left: -250px;
        overflow-y: auto;
        background: #37474F;
        -webkit-transition: all 0.5s ease;
        -moz-transition: all 0.5s ease;
        -o-transition: all 0.5s ease;
        transition: all 0.5s ease;
    }

    #sidebar header {
        background-color: #263238;
        font-size: 20px;
        line-height: 52px;
        text-align: center;
    }

    #sidebar header a {
        color: #fff;
        display: block;
        text-decoration: none;
    }

    #sidebar header a:hover {
        color: #fff;
    }

    #sidebar .nav{

    }

    #sidebar .nav a{
        background: none;
        border-bottom: 1px solid #455A64;
        color: #CFD8DC;
        font-size: 14px;
        padding: 16px 24px;
    }

    #sidebar .nav a:hover{
        background: none;
        color: #ECEFF1;
    }

    #sidebar .nav a i{
        margin-right: 16px;
    }

    .name{
        background: none;
        color: #777777;
        font-size: 17px;
        /*padding: 16px 24px;*/
        /*padding-top: 15px;*/
        /*padding-bottom: 15px;*/
        /*!*line-height: 20px;*!*/
        /*display: block;*/
        position: relative;
        display: block;
        padding: 10px 15px;
    }
</style>
<div id="viewport">
  <!-- Sidebar -->
  <%#= render partial: 'sidebar' %>
<!--  <br>-->
  <div class="container-fluid">
    <h1>Enrolled Courses:</h1>
    <br>
    <section class="container">
      <%
          @enrolled_courses.in_batches(of: 3) do |courses|
      %>
        <div class="row">
          <% courses.each do |course|%>
            <div class="col-sm-4 mb-3 d-flex align-items-stretch" style="margin-bottom: 1rem">
              <div class="card">
                <div class="card-body">
                  <h3 class="card-title"><%= course.name %></h3>
                  <p class="card-text"><%= course.description %></p>
                  <div class="price-div">
                    <span class="detail-link"><a href="#" class="">Details</a></span></div>
                </div>
              </div>
            </div>
          <%end %>
        </div>
        <br>
      <%end%>
    </section>
  </div>
</div>

<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content" style="background-color: #154F56">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title text-center heading" style="color: white">Thank You!</h3>
      </div>
      <div class="modal-body" id="thank-you">
        <section class="login-block">
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-12">
                <div class="auth-box card thank-you-card">
                  <div class="card-block">
                    <div class="row">
                      <div class="col-4 text-center">
                        Thank you for Enrollment.
                      </div>
                      <div class="col-4 text-center">
                        We will email you for further instructions.
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>

  </div>
</div>

<script>
    $(document).ready(function () {
        <% if params[:enrollment] == "yes" %>
        $('#myModal').modal('show');
        setTimeout(function() {
            $('#myModal').modal('hide');
        }, 2000);

        var uri = window.location.toString();
        if (uri.indexOf("?") > 0) {
            var clean_uri = uri.substring(0, uri.indexOf("?"));
            window.history.replaceState({}, document.title, clean_uri);
        }
        <% end %>

    });
</script>

app/views/users_home/get_profile.html.erb
<style>

    body{
        background:#f5f5f5;
    }
    /**
     * Panels
     */
    /*** General styles ***/
    .panel {
        box-shadow: none;
    }
    .panel-heading {
        border-bottom: 0;
    }
    .panel-title {
        font-size: 17px;
        color: white;
    }
    .panel-title > small {
        font-size: .75em;
        color: white;
    }
    .panel-body *:first-child {
        margin-top: 0;
    }
    .panel-footer {
        border-top: 0;
    }

    .panel-default > .panel-heading {
        color: #333333;
        background-color: transparent;
        border-color: rgba(0, 0, 0, 0.07);
    }

    form label {
        color: #FFFFFF;
        font-weight: 400;
    }

    .form-horizontal .form-group {
        margin-left: -15px;
        margin-right: -15px;
    }
    @media (min-width: 768px) {
        .form-horizontal .control-label {
            text-align: right;
            margin-bottom: 0;
            padding-top: 7px;
        }
    }

    .profile__contact-info-icon {
        float: left;
        font-size: 18px;
        color: #999999;
    }
    .profile__contact-info-body {
        overflow: hidden;
        padding-left: 20px;
        color: #999999;
    }
    .profile-avatar {
        width: 200px;
        position: relative;
        margin: 0px auto;
        margin-top: 196px;
        border: 4px solid #f3f3f3;
    }
    .panel {
        background: #154F56;
        /*color: #FFFFFF;*/
    }
</style>

<div id="viewport">

  <!-- Sidebar -->
  <div class="container-fluid bootstrap snippets bootdeys">
    <div class="row">
      <div class="col-xs-12 col-sm-9">
        <%= form_tag(update_user_profile_path(@user.id), method: :post, class: "form-horizontal") do %>
          <!--        <div class="panel panel-default">
                    <div class="panel-body text-center">
                      <img src="https://bootdey.com/img/Content/avatar/avatar6.png" class="img-circle profile-avatar" alt="User avatar">
                    </div>
                  </div>-->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title" style="color: white">User info</h4>
            </div>
            <div class="panel-body">

              <div class="form-group">
                <%= label_tag :first_name, "First Name", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                <%= text_field_tag :first_name, @user.first_name, class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :last_name, "Last Name", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= text_field_tag :last_name, @user.last_name, class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :institute, "Company or College or University Name", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= text_field_tag :institute, @user.institute, class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :position, "Position", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= text_field_tag :position, @user.position, class: "form-control" %>
                </div>
              </div>

            </div>
          </div>


          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">Contact info</h4>
            </div>
            <div class="panel-body">

              <div class="form-group">
                <%= label_tag :phone, "Mobile number", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= text_field_tag :phone, @user.phone, class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :phone, "Email", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= text_field_tag :email, @user.email, class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :address, "Address", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= text_area_tag :address, @user.address, class: "form-control" %>
                </div>
              </div>

            </div>
          </div>

          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">Security</h4>
            </div>
            <div class="panel-body">

              <div class="form-group">
                <%= label_tag :current_password, "Current Password", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= password_field_tag :current_password, @user.current_password, class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :password, "Password", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= password_field_tag :password, @user.password, class: "form-control" %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :password_confirmation, "Confirm New Password", class: "col-sm-2 control-label" %>
                <div class="col-sm-10">
                  <%= password_field_tag :password_confirmation, @user.password_confirmation, class: "form-control" %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-10 col-sm-offset-2">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <button type="reset" class="btn btn-default">Cancel</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>