config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_scope :user do
    # Redirects signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: "users/passwords",
    omniauth_callbacks: 'users/omniauth_callbacks',

  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get "/details", to: "home#details"
  get "/enrol_now/:course_id", to: "home#enrol_now", as: :enrol_now
  get "/contact", to: "home#contact", as: :contact
  post "/contact", to: "home#submit_contact_query", as: :submit_contact_query


  resources :courses
  get "/course_details", to: "courses#details"
  post "/enrol", to: "courses#enrol", as: :enrol
  get "/users/:id/dashboard", to: "users_home#dashboard", as: :user_dashboard
  get "/users/:id/dashboard", to: "users_home#dashboard", as: :users_root

  get "/users/:id/profile", to: "users_home#get_profile", as: :get_user_profile
  post "/users/:id/profile", to: "users_home#update_profile", as: :update_user_profile
  end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
    @course = Course.first
    render(:layout => "user_layout")
  end

  def show
    course_id = params[:id]
    @course = Course.find_by(id: course_id)
    respond_to do |format|
      format.json { render json: @course.as_json, status: :ok}
    end
  end

  def details
    course_id = params[:course]
    course = Course.find_by(id: course_id)

  end

  def enrol
    course_id = params[:course]
    @course = Course.find_by(id: course_id)
    unless current_user.courses.pluck(:id).include?(@course.id)
      current_user.enrollments.create(course_id: @course.id)
      CourseMailer.with(user: current_user, course: @course).enrol.deliver_now
    end
    redirect_to user_dashboard_path(current_user.id, enrollment: "yes")
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_all_courses.html.erb
<style>
    body {
        font-family: 'Roboto', sans-serif;
    }

    ul {
        list-style: none;
        display: flex;
        justify-content: flex-end;
    }

    figure img {
        width: 100%;
        height: auto;
    }

    figure {
        margin-bottom: 30px;
    }

    header nav {
        display: flex;
        justify-content: flex-end;
    }

    div > h1 {
        font-size: 1.8rem;
    }

    nav > p {
        cursor: pointer;
    }

    .pill-black, .pill-white {
        border: 0.5px solid;
        border-radius: 5px;
        text-align: center;
    }

    .pill-black {
        background-color: #000000;
        color: #FFFFFF;
    }

    footer {
        margin-top: 20px;
    }

    footer div {
        display: flex;
        align-items: center;
    }

    /* Customizations of Bootstrap classes */

    header .row {
        display: flex;
        align-items: center;
    }

    .col-sm-4 p {
        margin: 25px 20px 15px;
        min-width: 60px;
        padding: 1px;
    }

    section.container .row {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
    }

    .jumbotron h2 {
        background-color: #FFFFFF;
        display: inline-block;
        color: #36454F;
        font-weight: 700;
        padding: 10px 35px;
        border-radius: 5px;
    }

    .jumbotron h3 {
        color: #FFFFFF;
        font-weight: bold;
    }

    .btn-primary {
        color: #2e6da4;
        background-color: #FFFFFF;
    }

    .col-sm-1 img {
        min-width: 32px;
        min-height: 33px;
    }

    .card {
        background: #154F56;
        color: white;
        height: 34rem;
        border-radius: 1.25rem;
        padding: 10px;
    }

    .card-title {
        text-align: center;
        padding-top: 10px;
        font-weight: bold;
    }

    .price-div {
        padding-top: 10px;
        padding-left: 10px;
        padding-right: 10px;
    }

    .price {
        font-weight: bold;
        font-size: medium;
        float: left;
    }

    .detail-link {
        float: right;
    }

    .detail-link a {
        text-decoration: none;
        color: white;
        font-size: medium;
    }

    .detail-link a:hover {
        color: white;
        text-decoration: none;
        cursor: pointer;
    }

    .enrol-btn {
        margin-top: 32px;
        display: flex;
        justify-content: center;
        align-items: center;
    }

    .enrol-btn button {
        padding: 10px 20px 10px 20px;
        text-decoration: none;
        color: #154F56;
        font-weight: bold;
    }

    .auth-box {
        height: 22rem;
    }
    .modal-backdrop {
        z-index: 0;
    }
</style>
<section class="container">
  <%
    Course.all.in_batches(of: 3) do |courses|
  %>
    <div class="row">
      <% courses.each do |course| %>
        <div class="col-sm-4 mb-3 d-flex align-items-stretch" style="margin-bottom: 1rem">
          <div class="card">
            <div class="card-body">
              <h3 class="card-title"><%= course.name %></h3>
              <p class="card-text"><%= course.description %></p>
              <div class="price-div"><span class="price">Price: $<%= course.price %></span>
                <span class="detail-link"><a href="#" class="">Details</a></span></div>
              <div class="enrol-btn">
                <button type="button" class="en-btn btn btn-primary" data-toggle="modal" data-target="#myModal" data-course-id="<%= course.id %>">Enrol
                  Now
                </button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <br>
  <% end %>
</section>

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content" style="background-color: #154F56">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title text-center heading" style="color: white">Enrolment Form</h3>
      </div>
      <div class="modal-body" id="enrol-form">
        <section class="login-block">
          <div class="container-fluid">
            <div class="row">
              <div class="col-sm-12">
                <%= form_tag(enrol_path, method: :post, class: "md-float-material form-material") do %>
                  <div class="auth-box card">
                    <div class="card-block">
                      <div class="form-group form-primary">
                        <%= select_tag "course", options_for_select(Course.all.collect { |u| [u.name, u.id] }), { :class => "form-control form-select", prompt: 'Select Course' } %>
                      </div>
                      <div class="form-group form-primary">
                        <input disabled type="text" class="form-control disabled" name="price" value="" placeholder="Price" id="price">
                      </div>
                      <div class="form-group form-primary">
                        <input disabled type="text" class="form-control disabled" name="discount" value="" placeholder="Discount" id="discount">
                      </div>
                      <div class="row">
                        <div class="col-md-12">
                          <input id= "enrol" type="submit" class="btn btn-primary btn-md btn-block waves-effect text-center m-b-20" name="submit" value="Enrol Now">
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </section>
      </div>
    </div>

  </div>
</div>

<script>
        // $('#myModal').modal('hide');
        // $('body').removeClass('modal-open');
    // $('.modal-backdrop').remove();

    $('.en-btn').click(function () {
        $('select').val($(this).data("course-id")).trigger('change');
    })
    $('select').on('change', function () {
        $.ajax({
            type: "GET",
            url: "<%= courses_path %>/" + this.value,
            success: function (data) {
                $("#price").val("Price : $" + data.price);
                $("#discount").val("Price after " + data.discount + "% discount : $" + (parseInt(data.price) - (parseInt(data.price) * parseInt(data.discount) / 100)).toString());
            }
        });
    });
</script>

app/views/courses/index.html.erb
<style>
    body {
        font-family: 'Roboto', sans-serif;
    }

    ul {
        list-style: none;
        display: flex;
        justify-content: flex-end;
    }

    figure img {
        width: 100%;
        height: auto;
    }

    figure {
        margin-bottom: 30px;
    }

    header nav {
        display: flex;
        justify-content: flex-end;
    }

    div > h1 {
        font-size: 1.8rem;
    }

    nav > p {
        cursor: pointer;
    }
    .pill-black, .pill-white {
        border: 0.5px solid;
        border-radius: 5px;
        text-align: center;
    }

    .pill-black {
        background-color: #000000;
        color: #FFFFFF;
    }

    footer {
        margin-top: 20px;
    }

    footer div {
        display: flex;
        align-items: center;
    }

    /* Customizations of Bootstrap classes */

    header .row {
        display: flex;
        align-items: center;
    }

    .col-sm-4 p {
        margin: 25px 20px 15px;
        min-width: 60px;
        padding: 1px;
    }

    section.container .row {
        display: flex;
        flex-wrap: wrap;
        align-items: center;
        justify-content: center;
    }

    .jumbotron {
        display: flex;
        align-items: center;
        height: 350px;
        background-image: url("https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg");
        background-size: cover;
        background-position: center;
    }

    .jumbotron h2 {
        background-color: #FFFFFF;
        display: inline-block;
        color: #36454F;
        font-weight: 700;
        padding: 10px 35px;
        border-radius: 5px;
    }

    .jumbotron h3 {
        color: #FFFFFF;
        font-weight: bold;
    }

    .btn-primary {
        color: #2e6da4;
        background-color: #FFFFFF;
    }

    .col-sm-1 img {
        min-width: 32px;
        min-height: 33px;
    }

    .card {
        background:#154F56;
        color:white;
        height:31rem;
        border-radius: 1.25rem;
        padding: 10px;
    }
    .card-title{
        text-align: center;
        padding-top: 10px;
        font-weight: bold;
    }

    .price-div{
        padding-top: 10px;
        padding-left: 10px;
        padding-right: 10px;
    }
    .price{
        font-weight: bold;
        font-size: medium;
        float: left;
    }
    .detail-link{
        float: right;
    }
    .detail-link a {
        text-decoration: none;
        color: white;
        font-size: medium;
    }

    .detail-link a:hover {
        color: white;
        text-decoration: none;
        cursor: pointer;
    }
    .enrol-btn{
        margin-top: 32px;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .enrol-btn a{
        padding: 10px 20px 10px 20px;
        text-decoration: none;
        color: #154F56;
        font-weight: bold;
    }
</style>

<div>
<%= render partial: "courses/all_courses" %>
</div>